<script type="text/javascript">
   swfobject.registerObject("sacstate_video", "10.1.0", "http://www2.csus.edu/video/assets/players/10.1/scripts/expressInstall.swf");
</script>


<div id="strobeplayer">
  <object id="sacstate_video">



    <!--[if !IE]>-->
    <object  type="application/x-shockwave-flash" data="http://www2.csus.edu/video/assets/players/StrobeMediaPlayback.swf?src=<?php echo $this->teststream->rtmp_url; ?>&poster=http://www2.csus.edu/video/assets/players/10.1/images/billboard-default.png&bufferingOverlay=false&optimizeInitialIndex=true&minContinuousPlayback=30&bufferTime=12&initialBufferTime=8&expandedBufferTime=10" width="100%" height="480">
<param name="allowFullScreen" value="true"/>
 <!--<![endif]-->

   <param name="movie" value='http://www2.csus.edu/video/assets/players/StrobeMediaPlayback.swf?src=<?php echo $this->teststream->hds_url; ?>&poster=http://www2.csus.edu/video/assets/players/10.1/images/billboard-default.png' />
<param name="allowFullScreen" value="true"/>


      <div>

        <p>
          <video id="sacstate_video_html5" controls width="auto" height="100%" poster="http://www2.csus.edu/video/assets/players/10.1/images/billboard-default.png">
            <source src="<?php echo $this->teststream->hls_url; ?>">
            <source src="http://www2.csus.edu/video/assets/ams_setting_check.m4v">
            Your browser does not support Flash Player 10.1 or the HTML5 video element.
          </video>
        </p>
      </div>
      <!--[if !IE]>-->
    </object>
    <!--<![endif]-->
  </object>
</div>