<div class="row">
<div class="col-lg-12">
<div class="panel panel-default">
<div class="panel-heading">
<h2>Single Videos <?php echo $this->count; ?></h2>
</div>
<!-- /.panel-heading -->
<div class="panel-body">
<div class="table-responsive">
<table class="table table-striped table-bordered table-hover"
	id="dataTables-example">
	<thead>
		<tr>
			<th>Stream Name</th>
		</tr>
	</thead>
	<tbody>
		<?php echo $this->partialLoop('stream/partials/_streamPartialLoop.phtml', $this->listitems); ?>      
	</tbody>
</table>
</div>
<!-- /.table-responsive --></div>
<!-- /.panel-body --></div>
<!-- /.panel --></div>
<!-- /.col-lg-12 --></div>
<!-- /.row --> 
<script>
    $(document).ready(function() {
        $('#dataTables-example').dataTable({
        		    "iDisplayLength": 15
        			});
        
    });
    </script>