 <div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading"><h1>User List <?php echo 'Count: ' . $this->paginator->getPages()->totalItemCount; ?></h1> </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
        <div class="table-responsive">
          <table class="table table-striped table-bordered table-hover" id="dataTables-example">
            <thead>
              <tr>
                <th>Username</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Email</th>
                <th>Role</th>
              </tr>
            </thead>
            <tbody>
            <?php 
            	foreach($this->paginator as $record)
		    	{
					echo '<tr class="odd gradeX">';
		    		echo '<td>'.$record['username'].'</td>';
					echo '<td>'.$record['first_name'].'</td>';
					echo '<td>'.$record['last_name'].'</td>';
					echo '<td>'.$record['email'].'</td>';
					echo '<td>'.$record['role'].'</td>';
		    		echo '</tr>';
		    	}
		    ?>
              
            </tbody>
          </table>
        </div>
        <!-- /.table-responsive -->
      </div>
      <!-- /.panel-body --> 
    </div>
    <!-- /.panel --> 
  </div>
  <!-- /.col-lg-12 --> 
</div>
<!-- /.row -->

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {
        $('#dataTables-example').dataTable();
    });
    </script>
    