<tr>

	<td>
		<a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'index', 'cid' => $this->class_nbr, 'vid' => NULL)); ?>">
   			<?php echo $this->escape($this->course_number);  ?>
    	</a>
	</td>
	<td>
		<?php echo $this->escape($this->course_name);  ?>
	</td>
	<td>
		<a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'index', 'cid' => $this->class_nbr, 'vid' => NULL)); ?>">
   			<?php echo $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'index', 'cid' => $this->class_nbr, 'vid' => NULL)); ?>

    	</a>
	</td>
	<td>
		<?php echo $this->days; ?>
	</td>
	<td>
		<?php echo $this->start_time; ?>
	</td>
	<td>
		<?php echo $this->duration; ?>
	</td>	
</tr>