<div class="row">
  <div class="col-md-12">
    <h1>Embed Video </h1>
  </div>
</div>
<div class="row">
  <div class="col-md-4" id="osmfcontainer"> <?php echo $this->form; ?> </div>
  <div class="col-md-8" id="course_video_container"> 
    <script type="text/javascript">
   		swfobject.registerObject("sacstate_video", "10.1.0", "http://www2.csus.edu/video/assets/players/10.1/scripts/expressInstall.swf");
	</script>
    <div id="test_player"></div>
    <div id="strobeplayer">
      <object id="sacstate_video">
        <param name="movie" value="http://www2.csus.edu/video/assets/players/StrobeMediaPlayback.swf?src=http://video2.csus.edu/hds-vod/prj/disted/ams_web_archive/2014/ANTH0013/ANTH0013_2014_02_03_33577M.f4m&poster=&bufferingOverlay=false&optimizeInitialIndex=true&minContinuousPlayback=30&bufferTime=12&initialBufferTime=8&expandedBufferTime=10" />
        <param name="allowFullScreen" value="true"/>
        <!--[if !IE]>-->
        <object type="application/x-shockwave-flash" data="http://www2.csus.edu/video/assets/players/StrobeMediaPlayback.swf?src=http://video2.csus.edu/vod/prj/disted/ams_web_archive/2014/ANTH0013/ANTH0013_2014_02_03_33577P.f4m&poster=&bufferingOverlay=false&optimizeInitialIndex=true&minContinuousPlayback=30&bufferTime=12&initialBufferTime=8&expandedBufferTime=10" width="640"height="480">
          <param name="allowFullScreen" value="true"/>
          <!--<![endif]-->
          <div>
            <p>
              <video id="sacstate_video_html5" width="640" height="480" controls poster="">
                <source src="http://video2.csus.edu/hls-vod/prj/disted/ams_web_archive/2014/ANTH0013/ANTH0013_2014_02_03_33577M.m3u8">
                Your browser does not support Flash Player 10.1 or the HTML5 video element.</video>
            </p>
          </div>
          <!--[if !IE]>-->
        </object>
        <!--<![endif]-->
      </object>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12" id="">
    <hr>
    <textarea id="embed_target" rows="12" cols="120"></textarea>
  </div>
</div>







<script>

var width = '';
var height = '';
var rtmp_src = '';
var hds_src = '';
var hls_src = '';
var poster = '';

function getVars() {
	width    = $("#width").val();
	height   = $("#height").val();
	rtmp_src = $("#rtmp_src").val();
	hds_src  = $("#hds_src").val();
	hls_src  = $("#hls_src").val();
	poster   = $("#poster").val();
}

function embedPlayer() {
	
		var embedCode = '';
	    embedCode += '<div id="strobeplayer">';
	    embedCode += '<object id="sacstate_video">';
	    embedCode += '<param name="movie" value="http://www2.csus.edu/video/assets/players/StrobeMediaPlayback.swf';
	    embedCode += '?src=' + hds_src;
	    embedCode += '&poster=' + poster;
	    embedCode += '&bufferingOverlay=false';	    
	    embedCode += '&optimizeInitialIndex=true';
	    embedCode += '&minContinuousPlayback=30';
	    embedCode += '&bufferTime=12';
	    embedCode += '&initialBufferTime=8';
	    embedCode += '&expandedBufferTime=10" />';
		embedCode += '<param name="allowFullScreen" value="true"/>';
		embedCode += '<!--[if !IE]>-->';
	    embedCode += '<object type="application/x-shockwave-flash" data="http://www2.csus.edu/video/assets/players/StrobeMediaPlayback.swf';
	    embedCode += '?src=' + rtmp_src;
	    embedCode += '&poster=' + poster;
	    embedCode += '&bufferingOverlay=false';
	    embedCode += '&optimizeInitialIndex=true';
	    embedCode += '&minContinuousPlayback=30';		    
	    embedCode += '&bufferTime=12';
	    embedCode += '&initialBufferTime=8';
	    embedCode += '&expandedBufferTime=10" ';
	    embedCode += 'width="' + width + '"';
	    embedCode += 'height="' + height + '"';
	    embedCode += '>';
	    embedCode += '<param name="allowFullScreen" value="true"/>';
		embedCode += '<!--<![endif]-->';
		embedCode += '<div>';
		embedCode += '<p>';
		embedCode += '<video id="sacstate_video_html5" width="'+ width +'" height="'+ height +'" controls poster="'+ poster +'">';
		embedCode += '<source src="'+ hls_src+'">';
		embedCode += 'Your browser does not support Flash Player 10.1 or the HTML5 video element.';
		embedCode += '</video>';
		embedCode += '</p>';
		embedCode += '</div>';
		embedCode += '<!--[if !IE]>-->';
		embedCode += '</object>';
		embedCode += '<!--<![endif]-->';
		embedCode += '</object>';
		embedCode += '</div>';
		

	    embedCode += '';
	    embedCode += '';
	    embedCode += '';
	    embedCode += '';
	    embedCode += '';
	    embedCode += '';

		$("#embed_target").html(embedCode).text();	
		
}

function generateCode() {
	getVars();
	embedPlayer();
}



$( "#target" ).submit(function( event ) {
	generateCode();
	event.preventDefault();
});
</script>

