 <div class="container">

      <div class="row row-offcanvas row-offcanvas-right">

        <div class="col-xs-12 col-sm-9">
          <p class="pull-right visible-xs">
            <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
          </p>
          <div class="jumbotron">
            <h1>Course Videos Admin</h1>
            <p>This is an example to show the potential of an offcanvas layout pattern in Bootstrap. Try some responsive-range viewport sizes to see it in action.</p>
          </div>
          <div class="row">
            <div class="col-6 col-sm-6 col-lg-4">
              <h2>Load Courses</h2>
              <p><a class="btn btn-default" href="/admin/insertcourses" role="button">Load Courses &raquo;</a></p>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              
            </div><!--/span-->
            <div class="col-6 col-sm-6 col-lg-4">
              <h2>Load Videos</h2>
              <p><a class="btn btn-default" href="/admin/insertvideos" role="button">Load Videos &raquo;</a></p>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>

            </div><!--/span-->
            <div class="col-6 col-sm-6 col-lg-4">
              <h2>Users</h2>
              <p><a class="btn btn-default" href="#" role="button">Add User &raquo;</a></p>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>

            </div><!--/span-->
            <div class="col-6 col-sm-6 col-lg-4">
              <h2>Statistics</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn btn-default" href="#" role="button">View Statistics &raquo;</a></p>
            </div><!--/span-->
            <div class="col-6 col-sm-6 col-lg-4">
              <h2>Clean Cache</h2> 
                      <p><a class="btn btn-default" href="/admin/cleancache" role="button">Clean Cache &raquo;</a></p>
                                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>              
            </div><!--/span-->
            <div class="col-6 col-sm-6 col-lg-4">
              <h2>Logs</h2>
              <p>Error Log</p>
              <p>Application Log</p>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn btn-default" href="#" role="button">View Logs &raquo;</a></p>
            </div><!--/span-->
          </div><!--/row-->
        </div><!--/span-->

        <?php echo $this->partial('index/partials/_main_nav.phtml'); ?>
      </div><!--/row-->


    </div><!--/.container-->