 <div class="container">
  <div class="jumbotron-wrapper">
          	<div class="jumbotron">
            	<h1>Course Videos Admin</h1>
            	<p><?php echo $this->currentSemester; ?> <?php echo $this->currentYear; ?> Courses: <?php echo $this->courseCount; ?> Videos: <?php echo $this->videoCount; ?></p>
          	</div>
          </div>
 	<div class="row">
        <div class="col-md-4">
          <div class="content-module">
              		<h2>Ingest Data</h2>
              		<p>
              			<a class="btn btn-default" href="<?php echo $this->baseUrl(); ?>/admin/index/insertcourses" role="button">Load Courses &raquo;</a>
              		</p>
              		<p>
              			<a class="btn btn-default" href="<?php echo $this->baseUrl(); ?>/admin/index/insertvideos" role="button">Load Videos &raquo;</a>
              		</p>
              		<p>Reads the .csv files from /data/video/data/csv/ and then parses the data, and finally inserts it into a MySql database.</p>
              	</div>
        </div>
        <div class="col-md-4">
         <div class="content-module">
              <h2>Video Courses</h2>
              <p><a class="btn btn-default" href="<?php echo $this->baseUrl(); ?>/admin/index/courselist" role="button">Courselist &raquo;</a></p>
              <ul>
              	<li>Course count: <?php echo $this->courseCount; ?></li>
              	<li>Video count: <?php echo $this->videoCount; ?></li>
              </ul>
              </div>
       </div>
        <div class="col-md-4">
         <div class="content-module">
              <h2>Users</h2>
              <p><a class="btn btn-default" href="<?php echo $this->baseUrl(); ?>/admin/index/register" role="button">Add User &raquo;</a></p>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
				</div>
        </div>
      </div>
      
 	<div class="row">
        <div class="col-md-4">
          <div class="content-module">
              <h2>Statistics</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn btn-default" href="#" role="button">View Statistics &raquo;</a></p>
            </div>
        </div>
        <div class="col-md-4">
         <div class="content-module">
              <h2>Clean Cache</h2> 
                      <p><a class="btn btn-default" href="<?php echo $this->baseUrl(); ?>/admin/index/cleancache" role="button">Clean Cache &raquo;</a></p>
                                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>              

              </div>
       </div>
        <div class="col-md-4">
         <div class="content-module">
              <h2>Testing</h2>
              <p>Error Log</p>
              <p>Application Log</p>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn btn-default" href="#" role="button">View Logs &raquo;</a></p>
          </div>
        </div>
      </div>      
      

    </div><!--/.container-->