<div class="container">
	<div class="row">
		<h1>Streaming Videos List <?php echo 'Count: ' . $this->paginator->getPages()->totalItemCount; ?></h1>
		<ul>
		<?php 
		foreach($this->paginator as $record)
		    {
				echo '<li>';
		    	echo $record['start_dt'];
				echo '</li>';
		    }
		    ?>
		</ul>
    <?php echo  $this->paginationControl($this->paginator, 'Sliding', 'index/partials/pagination.phtml'); ?>
	</div>
</div>