<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h1>Playlists</h1>
			</div>
			<!-- /.panel-heading -->
			<div class="panel-body">
				<p>
				<?php echo $this->form; ?>
				</p>
				
			</div>
		</div>
	</div>
</div>

<div class="row">
<div class="col-lg-12">
<div class="panel panel-default">
<div class="panel-heading">
<h2>Playlists <?php echo $this->count; ?></h2>
</div>
<!-- /.panel-heading -->
<div class="panel-body">
<div class="table-responsive">
<table class="table table-striped table-bordered table-hover"
	id="dataTables-example">
	<thead>
		<tr>
			<th>Playlist Name</th>
		</tr>
	</thead>
	<tbody>
				            <?php echo $this->partialLoop('playlist/partials/_playlistPartialLoop.phtml', $this->playlists); ?>      
			            </tbody>
</table>
</div>
<!-- /.table-responsive --></div>
<!-- /.panel-body --></div>
<!-- /.panel --></div>
<!-- /.col-lg-12 --></div>
<!-- /.row --> <!-- Page-Level Demo Scripts - Tables - Use for reference -->
<script>
    $(document).ready(function() {
        $('#dataTables-example').dataTable({
        		    "iDisplayLength": 15
        			});
        
    });
    </script>