<li class="ss-coursevideos-metadata">
 <h4>
        <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index', 'cid' => $this->course_id, 'sid' => $this->section, 'vid' => $this->id)); ?>">
   <?php echo $this->escape($this->course_name); ?> Section: <?php echo $this->escape($this->section); ?>
        </a>
 </h4>
	<p>Available: <?php echo $this->escape($this->days); ?> <?php echo $this->escape($this->start_dt); ?></p>
</li>