<li>
	
	<div class="ss-videogallery-metadata clearfix"><span class="float-left span-3"><img alt="alt text" src="http://www.csus.edu/cached/Colleges/2.0/assets/images/billboard-thumbnail.png"/></span>
    	<h4>
    		<a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index', 'cid' => $this->course_id, 'sid' => $this->section, 'vid' => NULL)); ?>#mainContent">
			<?php echo $this->escape($this->course_number); ?>  <?php echo $this->escape($this->course_name); ?> Section <?php echo $this->escape($this->section); ?>
		</a>
		</h4>
    	<p><?php echo $this->escape($this->instructor); ?><br/>
    	<?php echo $this->escape($this->semester);  ?> <?php echo $this->escape($this->year); ?></p>
        <p><?php echo $this->escape($this->description); ?></p>
    </div>
    
</li>

