
  <nav>
    <ul class="nav nav-pills nav-stacked nav-justified">
      <li><a href="http://www2.csus.edu/video/index/live1/" id="live_streaming_link">Live Streaming</a></li>
      <li><a href="http://www.csus.edu/atcs/tools/digitalmedia/index.stm" id="digital_media_link">Digital Media</a></li>
      <li><a href="http://www.csus.edu/atcs/tools/mediaserver/index.stm" id="faculty_media_server_link">Faculty Media Server</a></li>
      <li><a href="http://www.csus.edu/irt/ServiceDesk/Support/videostreaming/index.html" id="streaming_support_link">Streaming Support</a></li>      
      <li><a href="mailto:servicedesk@csus.edu" id="email_service_desk_link">Email Service Desk</a></li>
    </ul>
  </nav>
