<script type="text/javascript">
	swfobject.registerObject("sacstate_video", "10.1.0", "expressInstall.swf");
</script>
  <div class="ss-videoplayer backdrop">
  <object id="sacstate_video" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="640" height="480">
		<param name="movie" value="http://media1.csus.edu:8080/prj/test/t7/videoPlayer/swfs/SampleMediaPlayback.swf?src=http://video2.csus.edu/hds-vod/prj/disted/ams_web_archive/2013/TESTs1/TESTs1_2013_08_09M.f4m&poster=http://www2.csus.edu/video/assets/images/poster_frame_tests1.jpg" />
        <!--[if !IE]>-->
		<object type="application/x-shockwave-flash" data="http://media1.csus.edu:8080/prj/test/t7/videoPlayer/swfs/SampleMediaPlayback.swf?src=http://video2.csus.edu/vod/prj/disted/ams_web_archive/2013/TESTs1/TESTs1_2013_08_09P.f4m&poster=http://www2.csus.edu/video/assets/images/poster_frame_tests1.jpg" width="640" height="480">
		<!--<![endif]-->
		
		<div>
			<h1>Video name</h1>
			<p><video controls width="640" height="360" poster="http://www2.csus.edu/video/assets/images/poster_frame_tests1.jpg">
               <source src="http://video2.csus.edu/hls-vod/prj/disted/ams_web_archive/2013/TESTs1/TESTs1_2013_08_09M.m3u8">   
                     
                    Your browser does not support Flash Player 10.1 or the HTML5 video element.
                    </video>
               </p>
                    
		</div>
		<!--[if !IE]>-->
		</object>
		<!--<![endif]-->
	</object>
	
	</div>