<script type="text/javascript">
    swfobject.registerObject("sacstate_video", "10.1.0", "http://www2.csus.edu/video/assets/players/10.1/scripts/expressInstall.swf");            
</script>

<div id="strobeplayer">
  <object id="sacstate_video">


   <!--[if !IE]>-->
<object type="application/x-shockwave-flash" data="http://www2.csus.edu/video/assets/players/10.1/SampleMediaPlayback.swf?src=http://video2.csus.edu/manifests/live_rtmp_multi_event1.f4m&poster=http://www2.csus.edu/video/assets/images/billboard-default.png" width="100%" height="460">
<param name="allowFullScreen" value="true"/>
 <!--<![endif]-->

   <param name="movie" value="http://www2.csus.edu/video/assets/players/10.1/SampleMediaPlayback.swf?src=http://video2.csus.edu/manifests/live_hds_multi_event1.f4m&poster=http://www2.csus.edu/video/assets/images/billboard-default.png" />
<param name="allowFullScreen" value="true"/>
<div>

<p><video controls width="640" height="480" poster="http://www2.csus.edu/video/assets/players/10.1/images/billboard-default.png">
          <source src="http://video2.csus.edu/manifests/live_hls_multi_event1.m3u8">
       <source src="http://www2.csus.edu/video/assets/ams_setting_check.m4v">
   
                    Your browser does not support Flash Player 10.1 or the HTML5 video element.
                    </video>
       </p>

</div>
<!--[if !IE]>-->
</object>
<!--<![endif]-->
</object>

</div>