<script type="text/javascript">
   swfobject.registerObject("sacstate_video", "10.1.0", "http://www2.csus.edu/video/assets/players/10.1/scripts/expressInstall.swf");
</script>


<div id="strobeplayer">
  <object id="sacstate_video" >
   <param name="movie" value='http://www2.csus.edu/video/assets/players/StrobeMediaPlayback.swf?src=http://www2.csus.edu/video/assets/ams_welcome.m4v&poster=http://www2.csus.edu/video/assets/players/10.1/images/billboard-default.png&bufferingOverlay=false&optimizeInitialIndex=true&minContinuousPlayback=30&bufferTime=12&initialBufferTime=8&expandedBufferTime=10' />
<param name="allowFullScreen" value="true"/>
    <!--[if !IE]>-->
    <object type="application/x-shockwave-flash" data="http://www2.csus.edu/video/assets/players/StrobeMediaPlayback.swf?src=http://www2.csus.edu/video/assets/ams_welcome.m4v&poster=http://www2.csus.edu/video/assets/players/10.1/images/billboard-default.png&bufferingOverlay=false&optimizeInitialIndex=true&minContinuousPlayback=30&bufferTime=12&initialBufferTime=8&expandedBufferTime=10" width="100%" height="460px">
<param name="allowFullScreen" value="true"/>     
 <!--<![endif]-->
      
      <div>
        <p>
          <video controls poster="http://www.csus.edu/cached/Colleges/2.0/assets/media/billboard/billboard-default.png">
            <source src="http://www2.csus.edu/video/assets/ams_welcome.m4v">
            Your browser does not support Flash Player 10.1 or the HTML5 video element. 
   
          </video>
        </p>
      </div>
      <!--[if !IE]>-->
    </object>
    <!--<![endif]-->
  </object>
</div>

