<div class="row">
	<div class="col-lg-12">
    	<div class="panel panel-default">
	      	<div class="panel-heading">
	      		<h1>Streaming Video Course List <?php echo $this->courseCount; ?></h1>
      		</div>
      		<!-- /.panel-heading -->
      		<div class="panel-body">
        		<div class="table-responsive">
          			<table class="table table-striped table-bordered table-hover" id="dataTables-example">
			            <thead>
			              <tr>
			                <th>Course Number</th>
			                <th>Course Name</th>
			                <th>Cousre URL</th>
			                <th>Days</th>
			                <th>Start Time</th>
			                <th>Duration</th>
			              </tr>
			            </thead>
			            <tbody>
				            <?php echo $this->partialLoop('index/_courseListBrief.phtml', 'admin', $this->courses); ?>      
			            </tbody>
          			</table>
        		</div>
        		<!-- /.table-responsive -->
      		</div>
      		<!-- /.panel-body --> 
    	</div>
    	<!-- /.panel --> 
  	</div>
  	<!-- /.col-lg-12 --> 
</div>
<!-- /.row -->

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {
        $('#dataTables-example').dataTable({
        		    "iDisplayLength": 50
        			});
        
    });
    </script>
    