<div class="mainRegion">

<p>Computer Count: <?php echo $this->computerCount; ?></p>
<ul>
	<li>Chrome</li>
	<li>Firefox</li>
	<li>IE</li>
	<li>Safari</li>
</ul>
<p>Phone Count: <?php echo $this->phoneCount; ?></p>
<ul>
	<li>iOS</li>
	<li>Android</li>
	<li>Windows</li>
	<li>Blackberry</li>
</ul>
<p>Tablet Count: <?php echo $this->tabletCount; ?></p>
<ul>
	<li>iPad</li>
	<li>Samsung</li>
	<li>Kindle</li>
	<li>Nexus</li>
	<li>Other</li>
</ul>









</div>