
    
<header class="headingRegion"><h1>Video Page Loads by Device Type</h1></header>    
<div class="mainRegion whiteBg  span-24 last">

<!--Div that will hold the pie chart-->
<div id="chart_div" class="span-24 last">
	<?php echo $this->chart; ?>
</div>

<div class="span-8">
<h3>Computer Count: <?php echo $this->computerCount; ?></h3>
<table>
  <tr>
	<td>IE</td><td><?php echo $this->computerIeCount; ?></td>
  </tr>
  <tr>
	<td>Firefox</td><td><?php echo $this->computerFirefoxCount; ?></td>
  </tr>
  <tr>
	<td>Chrome</td><td><?php echo $this->computerChromeCount; ?></td>
  </tr>
  <tr>
	<td>Safari</td><td><?php echo $this->computerSafariCount; ?></td>
  </tr>   
  <tr>
	<td>Unknown</td><td><?php echo $this->computerUnknownCount; ?></td>
  </tr> 
</table>

</div>


<div class="span-8">
<h3>Phone Count: <?php echo $this->phoneCount; ?></h3>
<table>
  <tr>
	<td>IE</td><td><?php echo $this->phoneIeCount; ?></td>
  </tr>
  <tr>
	<td>Firefox</td><td><?php echo $this->phoneFirefoxCount; ?></td>
  </tr>
  <tr>
	<td>Chrome</td><td><?php echo $this->phoneChromeCount; ?></td>
  </tr>
  <tr>
	<td>Safari</td><td><?php echo $this->phoneSafariCount; ?></td>
  </tr>   
  <tr>
	<td>Unknown</td><td><?php echo $this->phoneUnknownCount; ?></td>
  </tr> 
</table>
</div>

<div class="span-8 last">
<h3>Tablet Count: <?php echo $this->tabletCount; ?></h3>
<table>
  <tr>
	<td>IE</td><td><?php echo $this->tabletIeCount; ?></td>
  </tr>
  <tr>
	<td>Firefox</td><td><?php echo $this->tabletFirefoxCount; ?></td>
  </tr>
  <tr>
	<td>Chrome</td><td><?php echo $this->tabletChromeCount; ?></td>
  </tr>
  <tr>
	<td>Safari</td><td><?php echo $this->tabletSafariCount; ?></td>
  </tr>   
  <tr>
	<td>Unknown</td><td><?php echo $this->tabletUnknownCount; ?></td>
  </tr> 
</table>
</div>


</div>