
    
<header class="headingRegion"><h1>Video Page Loads by Device Type</h1></header>    
<div class="mainRegion whiteBg  span-24 last">

<div class="span-4">
<p>Computer Count: <?php echo $this->computerCount; ?></p>
<table>
  <tr>
	<td>IE</td><td><?php echo $this->computerIeCount; ?></td>
  </tr>
  <tr>
	<td>Firefox</td><td><?php echo $this->computerFirefoxCount; ?></td>
  </tr>
  <tr>
	<td>Chrome</td><td><?php echo $this->computerChromeCount; ?></td>
  </tr>
  <tr>
	<td>Safari</td><td><?php echo $this->computerSafariCount; ?></td>
  </tr>   
  <tr>
	<td>Unknown</td><td><?php echo $this->computerUnknownCount; ?></td>
  </tr> 
</table>

<ul>
	<li>Chrome: </li>
	<li>Firefox</li>
	<li>IE: <?php echo $this->computerIeCount; ?></li>
	<li>Safari</li>
</ul>
<p>Phone Count: <?php echo $this->phoneCount; ?></p>
<ul>
	<li>Chrome</li>
	<li>Firefox</li>
	<li>IE</li>
	<li>Safari</li>
</ul>
<p>Tablet Count: <?php echo $this->tabletCount; ?></p>
<ul>
	<li>Chrome</li>
	<li>Firefox</li>
	<li>IE</li>
	<li>Safari</li>
</ul>
</div>


<!--Div that will hold the pie chart-->
<div id="chart_div" class="span-20 last">
	<?php echo $this->chart; ?>
</div>

<div id="computerCount" style="display:none;"><?php echo $this->computerCount; ?></div>
<div id="phoneCount" style="display:none;"><?php echo $this->phoneCount; ?></div>
<div id="tabletCount" style="display:none;"><?php echo $this->tabletCount; ?></div>




</div>


    