<div class="container">
	<div class="row">
		<?php if ($this->course) {
			echo '<h1>'.$this->course->course_name. '</h1>'; 
			} else {
			  	echo '<h1>Sac State Streaming Video</h1>';
		}?>
	</div>


	<div class="row ss-videoplayer backdrop">
   		<div class="col-md-8" id="osmfcontainer">
	
		  	<?php if ($this->video) {
				echo $this->partial('index/_osmfplayer.phtml', 'default', array('course' => $this->course, 'video' => $this->video));
				echo '<em>'.$this->video['start_dt'] .'</em>';
			} else {
				echo $this->partial('index/_osmfplayerFallback.phtml');
			}?>
	
			<h2><?php echo $this->course->course_number; ?> Section: <?php echo $this->course->class_section; ?>
			<?php echo $this->course->semester; ?> <?php echo $this->course->year; ?></h2>
			<p >
			  <em>Instructor: <?php echo $this->course->instructor; ?></em>
			  <br/>
			  <?php echo $this->course->course_description; ?>
			</p>
   		</div>

    
 		<div class="col-md-4 ss-coursevideos-list" id="course_video_container">
 			<h3><?php echo $this->course->semester; ?> <?php echo $this->course->year; ?> Videos</h3>
 			<div class="info-block">
 				<em>Most Recent Video</em>
 				<p>
 					<a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'index', 'cid' => $this->recentVideo['class_nbr'], 'vid' => $this->recentVideo['id'])); ?>">
			  			<?php echo $this->recentVideo['recorded_available_datetime']; ?>
			  		</a>
		  		</p>
 			</div>
 			<div class="info-block">
 				<em>Next Live Stream on:</em>
 					<p>
						<a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'live', 'cid' => null, 'vid' => null)); ?><?php echo $this->course->studio; ?>">
			  			<?php echo $this->recentVideo['days']; ?> <?php echo $this->course->start_time; ?>
	  				</a>
	  			</p>
 			</div>
 			<h4>Recorded Videos</h4>
	 		
		    <?php if ($this->course) {
		    	echo '<ul>';
		    	echo $this->partialLoop('index/_courseVideoLoop.phtml', 'default', $this->coursevideos);
		    	//echo $this->partialLoop('index/_courseVideoLoop.phtml', 'default', array('coursevideos' => $this->coursevideos, 'linkEnabled' => $this->linkEnabled));
		    	echo '</ul>';
		    
			  } else {
			    echo '<h3>Course Videos</h3>';
			  }	?>
   		</div>
	</div>
</div>
