<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading"> <h1>Streaming Videos List <?php //echo 'Count: ' . $this->paginator->getPages()->totalItemCount; ?></h1> </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
        <div class="table-responsive">
          <table class="table table-striped table-bordered table-hover" id="dataTables-example">
            <thead>
              <tr>
                <th>Course Number</th>
                <th>Start Date</th>
                <th>Days</th>
                <th>Studio</th>
                <th>Course ID</th>
                <th>Class Number</th>
                <th>Start Time</th>
                <th>Available</th>
              </tr>
            </thead>
            <tbody>
            <?php 
   			foreach($this->videos as $record)
		    {
				echo '<tr>';
		    	echo '<td>'.$record['course_number'].'</td>';
				echo '<td>'.$record['start_dt'].'</td>';
		    	echo '<td>'.$record['days'].'</td>';
		    	echo '<td>'.$record['studio'].'</td>';
		    	echo '<td>'.$record['course_id'].'</td>';
		    	echo '<td>'.$record['class_nbr'].'</td>';
		    	echo '<td>'.$record['live_start_datetime'].'</td>';
		    	echo '<td>'.$record['recorded_available_datetime'].'</td>';
				echo '</tr>';
		    }
		    ?>
            </tbody>
          </table>
        </div>
        <!-- /.table-responsive -->
      </div>
      <!-- /.panel-body --> 
    </div>
    <!-- /.panel --> 
  </div>
  <!-- /.col-lg-12 --> 
</div>
<!-- /.row -->

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {
        $('#dataTables-example').dataTable({
		    "iDisplayLength": 45
			});
    });
    </script>
    