<ul>
  	<li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'test', 'action' => 'live1')); ?>">Live Stream 1 - Classroom Studio A</a></li>
  	<li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'test', 'action' => 'live2')); ?>">Live Stream 2 - Classroom Studio D</a></li>
  	<li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'test', 'action' => 'live3')); ?>">Live Stream 3 - Classroom Studio E</a></li>
  	<li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'test', 'action' => 'live4')); ?>">Special Event</a></li>
</ul>