<script type="text/javascript">
   swfobject.registerObject("sacstate_video", "10.1.0", "http://www2.csus.edu/video/assets/players/10.1/scripts/expressInstall.swf");
</script>
  <div class="ss-videoplayer backdrop">
   <h2><?php echo $this->course_number; ?> <?php echo $this->days; ?> <?php echo $this->start_dt; ?></h2>
  <object id="sacstate_video"  width="640" height="480">

   <param name="movie" value="http://www2.csus.edu/video/assets/players/10.1/StrobeMediaPlayback.swf?src=http://video2.csus.edu/hds-vod/prj/disted/ams_web_archive/2013/<?php echo $this->course_number; ?>/<?php echo $this->course_number; ?>_<?php echo $this->filename; ?>_<?php echo $this->section; ?>M.f4m" />
<param name="flashvars"
       value="poster=http://www2.csus.edu/video/assets/images/billboard-default.png&streamType=live&loop=false&autoPlay=true&playButtonOverlay=true&controlBarAutoHide=true&allowFullScreen=true&autoPlay=true"> </param>


        <!--[if !IE]>-->
   <object type="application/x-shockwave-flash" data="http://www2.csus.edu/video/assets/players/10.1/StrobeMediaPlayback.swf?src=http://video2.csus.edu/vod/prj/disted/ams_web_archive/2013/<?php echo $this->course_number; ?>/<?php echo $this->course_number; ?>_<?php echo $this->filename; ?>_<?php echo $this->section; ?>P.f4m" width="640" height="480">

<param name="flashvars"
       value="poster=http://www2.csus.edu/video/assets/images/billboard-default.png&streamType=live&loop=false&autoPlay=true&playButtonOverlay=true&controlBarAutoHide=true&allowFullScreen=true&autoPlay=true"> </param>



   <!--<![endif]-->
   
   <div>
   <p><video controls width="640" height="480" poster="http://www.csus.edu/cached/Colleges/2.0/assets/media/billboard/billboard-default.png">
               <source src="http://video2.csus.edu/hls-vod/prj/disted/ams_web_archive/2013/<?php echo $this->course_number; ?>/<?php echo $this->course_number; ?>_<?php echo $this->filename; ?>_<?php echo $this->section; ?>M.m3u8">           
                    Your browser does not support Flash Player 10.1 or the HTML5 video element.
                    </video>
               </p>
                    
   </div>
   <!--[if !IE]>-->
   </object>
   <!--<![endif]-->
   </object>
   
   </div>
