<script type="text/javascript">
	swfobject.registerObject("sacstate_video", "10.1.0", "http://www2.csus.edu/video/assets/players/10.1/scritps/expressInstall.swf");
</script>
  <div class="ss-videoplayer backdrop large">
  <object id="sacstate_video"  width="750" height="422"  style="display:block; position:relative; width:750; margin-left:auto; margin-right:auto;" >
    <param name="movie"  value="http://www2.csus.edu/video/assets/players/10.1/SampleMediaPlayback.swf?src=http://video2.csus.edu/hds-vod/prj/test/pa/spring_comm_2013_05_24M.f4m&poster=http://www2.csus.edu/video/assets/images/pa_test_poster.jpg" />
    <param name="allowFullScreen" value="true"/>
        <!--[if !IE]>-->
		<object type="application/x-shockwave-flash" data="http://www2.csus.edu/video/assets/players/10.1/SampleMediaPlayback.swf?src=http://video2.csus.edu/vod/prj/test/pa/spring_comm_2013_05_24P.f4m&poster=http://www2.csus.edu/video/assets/images/pa_test_poster.jpg" width="750" height="422">
   <param name="allowFullScreen" value="true"/>
		<!--<![endif]-->
		
		<div>
			<h1>Spring 2013 Commencement</h1>
			<p><video controls width="750" height="422" poster="http://www2.csus.edu/video/assets/images/pa_test_poster.jpg">
                           <source src="http://video2.csus.edu/hls-vod/prj/test/pa/spring_comm_2013_05_24M.m3u8">                          
                    Your browser does not support Flash Player 10.1 or the HTML5 video element.
<source src="http://www2.csus.edu/video/assets/ams_setting_check.m4v">
                    </video>
               </p>
                    
		</div>
		<!--[if !IE]>-->
		</object>
		<!--<![endif]-->
	</object>
	
	</div>