<script type="text/javascript">
	swfobject.registerObject("sacstate_video", "10.1.0", "http://www2.csus.edu/video/assets/players/10.1/scripts/expressInstall.swf");
</script>
  <div class="ss-videoplayer backdrop">
  <object id="sacstate_video"  width="640" height="480">
		<param name="movie" value="http://www2.csus.edu/video/assets/players/10.1/SampleMediaPlayback.swf?src=http://www2.csus.edu/video/assets/ams_welcome.m4v" />
<param name="allowFullScreen" value="true"/>

<param name="flashvars"
       value="poster=http://www2.csus.edu/video/assets/images/billboard-default.png&streamType=live&loop=false&autoPlay=false&playButtonOverlay=true&controlBarAutoHide=true"> </param>


        <!--[if !IE]>-->
		<object type="application/x-shockwave-flash" data="http://www2.csus.edu/video/assets/players/10.1/SampleMediaPlayback.swf?src=http://www2.csus.edu/video/assets/ams_welcome.m4v" width="640" height="480">
<param name="allowFullScreen" value="true"/>	
<param name="flashvars"
       value="poster=http://www2.csus.edu/video/assets/images/billboard-default.png&streamType=live&loop=false&autoPlay=false&playButtonOverlay=true&controlBarAutoHide=true"> </param>


	<!--<![endif]-->
		
		<div>
		       
			<p><video controls width="640" height="480" poster="http://www.csus.edu/cached/Colleges/2.0/assets/media/billboard/billboard-default.png">
               <source src="http://www2.csus.edu/video/assets/ams_welcome.m4v">   
                       
                    Your browser does not support Flash Player 10.1 or the HTML5 video element.
                    </video>
               </p>
                    
		</div>
		<!--[if !IE]>-->
		</object>
		<!--<![endif]-->
	</object>
	
	</div>