        <!-- Enable Browser History by replacing useBrowserHistory tokens with two hyphens -->
        <!-- BEGIN Browser History required section ${useBrowserHistory}>
        <link rel="stylesheet" type="text/css" href="history/history.css" />
        <script type="text/javascript" src="history/history.js"></script>
        <!${useBrowserHistory} END Browser History required section -->  
            
        <script type="text/javascript" src="swfobject.js"></script>
        <script type="text/javascript">
	   // For version detection, set to min. required Flash Player version, or 0 (or 0.0.0), for no version detection. 
	   var swfVersionStr = "${version_major}.${version_minor}.${version_revision}";
// To use express install, set to playerProductInstall.swf, otherwise the empty string. 
var xiSwfUrlStr = "${expressInstallSwf}";
var flashvars = {};
var params = {};
params.quality = "high";
params.bgcolor = "${bgcolor}";
params.allowscriptaccess = "sameDomain";
params.allowfullscreen = "true";
var attributes = {};
attributes.id = "${application}";
attributes.name = "${application}";
attributes.align = "middle";
swfobject.embedSWF(
		   "${swf}.swf", "flashContent", 
		   "${width}", "${height}", 
		   swfVersionStr, xiSwfUrlStr, 
		   flashvars, params, attributes);
// JavaScript enabled so display the flashContent div in case it is not replaced with a swf object.
swfobject.createCSS("#flashContent", "display:block;text-align:left;");
        </script>






<script type="text/javascript">
   swfobject.registerObject("sacstate_video", "10.1.0", "http://www2.csus.edu/video/assets/players/10.1/scripts/expressInstall.swf");
</script>




 <!-- SWFObject's dynamic embed method replaces this alternative HTML content with Flash content when enough 
             JavaScript and Flash plug-in support is available. The div is initially hidden so that it doesn't show
             when JavaScript is disabled.
        -->
        <div id="flashContent">
            <p>
                To view this page ensure that Adobe Flash Player version 
${version_major}.${version_minor}.${version_revision} or greater is installed. 
            </p>
            <script type="text/javascript"> 
  var pageHost = ((document.location.protocol == "https:") ? "https://" : "http://"); 
document.write("<a href='http://www.adobe.com/go/getflashplayer'><img src='" 
	       + pageHost + "www.adobe.com/images/shared/download_buttons/get_flash_player.gif' alt='Get Adobe Flash player' /></a>" ); 
            </script> 
        </div>
        
        <noscript>
            <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="${width}" height="${height}" id="${application}">
                <param name="movie" value="${swf}.swf" />
                <param name="quality" value="high" />
                <param name="bgcolor" value="${bgcolor}" />
                <param name="allowScriptAccess" value="sameDomain" />
                <param name="allowFullScreen" value="true" />
                <!--[if !IE]>-->
                <object type="application/x-shockwave-flash" data="${swf}.swf" width="${width}" height="${height}">
                    <param name="quality" value="high" />
                    <param name="bgcolor" value="${bgcolor}" />
                    <param name="allowScriptAccess" value="sameDomain" />
                    <param name="allowFullScreen" value="true" />
                <!--<![endif]-->
                <!--[if gte IE 6]>-->
                    <p> 
                        Either scripts and active content are not permitted to run or Adobe Flash Player version
	    ${version_major}.${version_minor}.${version_revision} or greater is not installed.
                    </p>
                <!--<![endif]-->
                    <a href="http://www.adobe.com/go/getflashplayer">
                        <img src="http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif" alt="Get Adobe Flash Player" />
                    </a>
                <!--[if !IE]>-->
                </object>
                <!--<![endif]-->
            </object>
        </noscript>    




<div class="ss-videoplayer backdrop">
   <h2><?php echo $this->course_number; ?> <?php echo $this->days; ?> <?php echo $this->start_dt; ?></h2>

  <object id="sacstate_video"  width="640" height="480">
 
 <!--[if !IE]>-->
    <object type="application/x-shockwave-flash" data="http://www2.csus.edu/video/assets/players/10.1/SampleMediaPlayback.swf?src=http://video2.csus.edu/vod/prj/disted/ams_web_archive/2013/<?php echo $this->course_number;?>/<?php echo $this->course_number;?>_<?php echo $this->filename;?>P.f4m&poster=http://www2.csus.edu/video/assets/players/10.1/images/billboard-default.png" width="640" height="480">
<param name="allowFullScreen" value="true"/>     
 <!--<![endif]-->

  <param name="movie" value='http://www2.csus.edu/video/assets/players/10.1/StrobeMediaPlayback.swf?src=http://video2.csus.edu/hds-vod/prj/disted/ams_web_archive/2013/<?php echo $this->course_number;?>/<?php echo $this->course_number;?>_<?php echo $this->filename;?>M.f4m&poster=http://www2.csus.edu/video/assets/players/10.1/images/billboard-default.png' />
<param name="allowFullScreen" value="true"/>
   
      
      <div>
        <p>
          <video controls width="640" height="360" poster="http://www.csus.edu/cached/Colleges/2.0/assets/media/billboard/billboard-default.png">
            <source src="http://video2.csus.edu/hls-vod/prj/disted/ams_web_archive/2013/<?php echo $this->course_number;?>/<?php echo $this->course_number;?>_<?php echo $this->filename;?>M.m3u8">
            Your browser does not support Flash Player 10.1 or the HTML5 video element. 
   
          </video>
        </p>
      </div>
      <!--[if !IE]>-->
    </object>
    <!--<![endif]-->
  </object>
</div>