<?php if ($this->course) {
    echo '<div class="span-24 last headingRegion"><h1>'.$this->course->course_name. ' Videos</h1>'; 
  } else {
    echo '<div class="span-24 last headingRegion"><h1>Sac State Streaming Video</h1></div>';
  }?>


<div class="span-24 last">
    <div class="span-17 .ss-videoplayer-container" id="osmfcontainer">
    <?php if ($this->video) {
    echo $this->partial('test/_osmfplayerMgmt.phtml', $this->video);
  } else {
    echo $this->partial('index/_osmfplayerFallback.phtml');
  }?>
  
  </div>
    
    <div class="span-7 last ss-coursevideos-list" id="course_video_container">
    <?php if ($this->course) {
    echo '<h3>'.$this->course->course_number. ' Videos</h3>'; 
  } else {
    echo '<h3>Course Videos</h3>';
  }?>
  
  
  
  <ul>
  <?php echo $this->partialLoop('index/_courseVideoLoopMgmt.phtml', $this->coursevideos);?>
       </ul>
       </div>
</div>