<script type="text/javascript">
   swfobject.registerObject("sacstate_video", "10.1.0", "http://www2.csus.edu/video/assets/players/10.1/scripts/expressInstall.swf");
</script>
  <div class="ss-videoplayer backdrop">
  <object id="sacstate_video"  width="640" height="480">
   <param name="movie" value="http://www2.csus.edu/video/assets/players/10.1/StrobeMediaPlayback.swf?src=http://video2.csus.edu/manifests/live_r\
tmp_multi_studio1.f4m&poster=http://www2.csus.edu/video/assets/images/billboard-default.png" />
<param name="allowFullScreen" value="true"/>


        <!--[if !IE]>-->
<object type="application/x-shockwave-flash" data="http://www2.csus.edu/video/assets/players/10.1/StrobeMediaPlayback.swf?src=http://video2.csus\
.edu/manifests/live_rtmp_multi_studio1.f4m&poster=http://www2.csus.edu/video/assets/images/billboard-default.png" width="640" height="480">
<param name="allowFullScreen" value="true"/>

 <!--<![endif]-->

<div>
<h1>Video name</h1>
<p><video controls width="640" height="360" poster="http://www2.csus.edu/video/assets/images/billboard-default.png">
               <source src="http://video2.csus.edu/manifests/live_hls_multi_studio1.m3u8">

                    Your browser does not support Flash Player 10.1 or the HTML5 video element.
                    </video>
               </p>

</div>
<!--[if !IE]>-->
</object>
<!--<![endif]-->
</object>

</div>