<script type="text/javascript">
	swfobject.registerObject("sacstate_video", "10.1.0", "expressInstall.swf");
</script>
  <div class="ss-videoplayer backdrop">
  <h2><?php echo $this->course_number; ?> <?php echo $this->days; ?> <?php echo $this->start_dt; ?></h2>
  <object id="sacstate_video" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="640" height="480">
		<param name="movie" value="http://media1.csus.edu:8080/prj/test/t7/videoPlayer/swfs/SampleMediaPlayback.swf?src=http://video2.csus.edu/hds-vod/prj/disted/ams_web_archive/2013/<?php echo $this->course_number; ?>/<?php echo $this->course_number; ?>_<?php echo $this->filename; ?>_<?php echo $this->section; ?>M.f4m&poster=http%3A%2F%2Fwww.csus.edu%2Fcached%2FColleges%2F2.0%2Fassets%2Fmedia%2Fbillboard%2Fbillboard-default.png" />
        <!--[if !IE]>-->
		<object type="application/x-shockwave-flash" data="http://media1.csus.edu:8080/prj/test/t7/videoPlayer/swfs/SampleMediaPlayback.swf?src=http://video2.csus.edu/vod/prj/disted/ams_web_archive/2013/<?php echo $this->course_number; ?>/<?php echo $this->course_number; ?>_<?php echo $this->filename; ?>_<?php echo $this->section; ?>P.f4m&poster=http%3A%2F%2Fwww.csus.edu%2Fcached%2FColleges%2F2.0%2Fassets%2Fmedia%2Fbillboard%2Fbillboard-default.png" width="640" height="480">
		<!--<![endif]-->
		
		<div>
			<p><video controls width="640" height="360" poster="http://www.csus.edu/cached/Colleges/2.0/assets/media/billboard/billboard-default.png">
               <source src="http://video2.csus.edu/hls-vod/prj/disted/ams_web_archive/2013/<?php echo $this->course_number; ?>/<?php echo $this->course_number; ?>_<?php echo $this->filename; ?>_<?php echo $this->section; ?>M.m3u8">           
                    Your browser does not support Flash Player 10.1 or the HTML5 video element.
                    </video>
               </p>
                    
		</div>
		<!--[if !IE]>-->
		</object>
		<!--<![endif]-->
	</object>
	
	</div>
