<div class="row">
<h1>Departments</h1>
<p>Add new department</p>
<form class="form-inline" role="form">
  <div class="form-group">
    <label class="sr-only" for="exampleInputEmail2">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail2" placeholder="Enter email">
  </div>
  <div class="form-group">
    <label class="sr-only" for="exampleInputPassword2">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword2" placeholder="Password">
  </div>
  <div class="checkbox">
    <label>
      <input type="checkbox"> Remember me
    </label>
  </div>
  <button type="submit" class="btn btn-default">Sign in</button>
</form>

<?php echo $this->form; ?>


</div>
<div class="row">
	<div class="col-lg-12">
    	<div class="panel panel-default">
	      	<div class="panel-heading">
	      		<h2>Department List <?php echo $this->count; ?></h2>
      		</div>
      		<!-- /.panel-heading -->
      		<div class="panel-body">
        		<div class="table-responsive">
          			<table class="table table-striped table-bordered table-hover" id="dataTables-example">
			            <thead>
			              <tr>
			                <th>Department </th>
			              </tr>
			            </thead>
			            <tbody>
				            <?php echo $this->partialLoop('department/partials/_departmentlist.phtml', $this->departments); ?>      
			            </tbody>
          			</table>
        		</div>
        		<!-- /.table-responsive -->
      		</div>
      		<!-- /.panel-body --> 
    	</div>
    	<!-- /.panel --> 
  	</div>
  	<!-- /.col-lg-12 --> 
</div>
<!-- /.row -->

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {
        $('#dataTables-example').dataTable({
        		    "iDisplayLength": 15
        			});
        
    });
    </script>
    