<div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
          <div class="list-group">
            <a href="<?php echo $this->baseUrl(); ?>/admin/index/index" class="list-group-item active">Admin Home</a>
            <a href="<?php echo $this->baseUrl(); ?>/admin/index/courselist" class="list-group-item">Course list</a>
            <a href="#" class="list-group-item">Users</a>
            <a href="#" class="list-group-item">Statistics</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
          </div>
        </div><!--/span-->