<div class="pageContextNavigation">
  <nav>
    <ul>
      <li><a href="http://www.csus.edu/videocourses/">Course Videos</a></li>
      <li><a href="http://www2.csus.edu/video/index/live1/">Live Streaming</a></li>
      <li><a href="http://www.csus.edu/atcs/tools/digitalmedia/index.stm">Digital Media</a></li>
      <li><a href="http://www.csus.edu/atcs/tools/mediaserver/index.stm">Faculty Media Server</a></li>
      <li><a href="http://www.csus.edu/sacct/support.stm">Ask a Consultant</a></li>
      <li><a href="http://www.csus.edu/irt/ServiceDesk/Support/videostreaming/index.html">Streaming Support</a></li>
      <li><a href="mailto:servicedesk@csus.edu">Email Service Desk</a></li>
    </ul>
  </nav>
</div>