<!-- css -->
<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet">
<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/smoothness/jquery-ui.min.css" rel="stylesheet" type="text/css" />
<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet">

<link href="<?php echo $this->baseUrl(); ?>/assets/css/bootstrap/admin-main.css" media="all" rel="stylesheet" type="text/css"/>

<link href="<?php echo $this->baseUrl(); ?>/assets/css/sb-admin-v2/css/plugins/timeline/timeline.css" media="all" rel="stylesheet" type="text/css"/>

<!-- SB Admin CSS - Include with every page -->
<link href="<?php echo $this->baseUrl(); ?>/assets/sb-admin-v2/css/sb-admin.css" media="all" rel="stylesheet" type="text/css"/>

