<!-- google anayltics --> 
<script src="http://www.google-analytics.com/ga.js" type="text/javascript"></script> 
<script type="text/javascript">

//<![CDATA[
  var _gaq = _gaq || [];

  _gaq.push(['_setAccount', 'UA-798015-8']);

  _gaq.push(['_trackPageview']);

	(function() {

    	var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;

    	ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';

    	var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);

  	})();

	$(function () {

  		var track = function(x,y) {

	    _gaq.push(['_trackEvent', 'Sacramento State Course Videos', x, y]);

  	};

  var track_region = function (selector, name) { 

    $(selector).live('click', function(e){

      var _t = $(this);

      track(name,  (_t.text() || _t.children('img:first').attr('alt')));

    })

  };

  

   track_region('#logo a', 'Logo');

   track_region('#secondaryGlobalNav li a', 'Secondary Nav Link');

   track_region('.subLinks li a', 'Secondary Sub Nav Link');

   track_region('.globalNavigation ul li a', 'Primary Navigation Link');

   track_region('#quickLinks-menu li a', 'Quicklinks Links');

   track_region('#course_videos_link', 'Course Videos link');

   track_region('#live_streaming_link', 'Live Streaming link');

   track_region('#digital_media_link', 'Digital Media link');

   track_region('#faculty_media_server_link', 'Faculty Media Server link');

   track_region('#ask_a_consultant_link', 'Ask A Consultant link');

   track_region('#streaming_support_link', 'Streaming Support link');

   track_region('#email_service_desk_link', 'Email Service Desk link');

   track_region('#facebook_link', 'Facebook link');

   track_region('#twitter_link', 'Twitter link');

   track_region('#youtube_link', 'YouTube link');

   track_region('#flickr_link', 'flickr link');



});



    //]]>

</script> 