<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>

<!-- SB Admin Scripts - Include with every page -->
<script src="<?php echo $this->baseUrl(); ?>/assets/sb-admin-v2/js/sb-admin.js" type="text/javascript"></script> 

<!-- Page-Level Plugin Scripts - Tables -->
<script src="<?php echo $this->baseUrl(); ?>/assets/sb-admin-v2/js/plugins/dataTables/jquery.dataTables.js" type="text/javascript"></script> 
<script src="<?php echo $this->baseUrl(); ?>/assets/sb-admin-v2/js/plugins/dataTables/dataTables.bootstrap.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl(); ?>/assets/sb-admin-v2/js/plugins/metisMenu/jquery.metisMenu.js" type="text/javascript"></script>

<script src="<?php echo $this->baseUrl(); ?>/assets/js/oocharts.min.js" type="text/javascript"></script> 