<div id="banner" class="banner">
<header class="ss-header">
		<!-- navbar -->
		<div id="ss_banner_nav">
		  <div class="navbar navbar-default ss-primary-nav" role="navigation">
		   
			<div class="navbar-header">
			  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"> 
			  	<span class="sr-only">Toggle navigation</span> 
			    <span class="icon-bar"></span> 
			    <span class="icon-bar"></span> 
			    <span class="icon-bar"></span> 
			  </button>
			  <a href="http://www.csus.edu/" title="Sacramento State Homepage">
			  	<img alt="Sacramento State logo" src="<?php echo $this->baseUrl(); ?>/assets/images/nick_logo_65.png"/>
			  </a> 
			</div>
			
		      <div class="collapse navbar-collapse">
		      <?php echo $this->loggedInUser(); ?>
		        <ul class="nav navbar-nav pull-right ss-primary-nav-links">
		          <li><a href="http://www.csus.edu/about/index.html">About</a></li>
		          <li><a href="http://www.csus.edu/academics/index.html">Academics</a></li>
		          <li><a href="http://www.csus.edu/admissions">Admissions</a></li>
		          <li><a href="http://www.hornetsports.com/">Athletics</a></li>
		          <li><a href="http://www.csus.edu/giving">Make A Gift</a></li>
		          <li class="dropdown"> <a href="#" class="dropdown-toggle quicklinks-button" data-toggle="dropdown">Quick Links <b class="caret"></b></a>
		            <ul class="quicklinks dropdown-menu">
		              <li><a href="http://www.csus.edu/about/calendars/">Calendars</a></li>
		              <li><a href="http://www.csus.edu/campusmap">Campus Map</a></li>
		              <li><a href="http://aaweb.csus.edu/catalog/default.html">Catalog</a></li>
		              <li><a href="http://www.collegeportraits.org/CA/CSUS">College Portrait</a></li>
		              <li><a href="http://www.csus.edu/Academics/index.html">Colleges &amp; Depts</a></li>
		              <li><a href="http://www.csus.edu/Technology/index.html">Computing &amp; Technology</a></li>
		              <li><a href="http://www.csus.edu/about/employment/">Jobs</a></li>
		              <li><a href="http://library.csus.edu/">Library</a></li>
		              <li><a href="http://online.csus.edu/">Online Courses (SacCT)</a></li>
		              <li><a href="https://www.saclink.csus.edu/">SacLink</a></li>
		            </ul>
		          </li>
		        </ul>
		      </div>
		   
		  </div>
		</div>
	
</header>
</div>