<!-- css -->
<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet">
<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet">

<link href="<?php echo $this->baseUrl(); ?>/assets/css/bootstrap/admin-main.css" media="all" rel="stylesheet" type="text/css"/>

<link href="<?php echo $this->baseUrl(); ?>/assets/css/bootstrap/playlist-main.css" media="all" rel="stylesheet" type="text/css"/>

<!-- full width pics css -->


