<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
<meta content="IE=Edge,chrome=1" http-equiv="X-UA-Compatible"/>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<title>Sacramento State Course Videos</title>

<!-- css -->
<link href="http://getbootstrap.com/dist/css/bootstrap.css" rel="stylesheet" type="text/css" />

<!-- 
<link href="http://www.csus.edu/cached/Colleges/2.0/assets/themes/responsive/css/bootstrap-responsive.min.css" rel="stylesheet" type="text/css" />
 -->


<link href="http://www.csus.edu/cached/Colleges/2.0/assets/css/monet-20-styles.css" media="all" rel="stylesheet" type="text/css"/>

<!-- page level css -->
<link href="<?php echo $this->baseUrl(); ?>/assets/css/video-styles.css" media="all" rel="stylesheet" type="text/css"/>
<link href="<?php echo $this->baseUrl(); ?>/assets/css/bootstrap/main.css" media="all" rel="stylesheet" type="text/css"/>
<!-- end css -->



<!-- javascript -->
<!-- Enable IE to recognize html5 elements -->
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>


<script src="//ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js"></script>


<script src="http://getbootstrap.com/dist/js/bootstrap.js"></script>


<!-- end javascript -->

</head>

<body>

<!--  #skip  Skip link as defined by webaim http://webaim.org/techniques/css/invisiblecontent/ -->
<div id="skip"><a href="#mainContent">Skip to Main Content</a></div>
<!-- end #skip --> 

<!-- #body container -->

<div class="container-fluid">
	<div class="row-fluid">
    	<div class="span12 banner" id="banner" role="banner">
    	
    		<div class="navbar">
        		<div class="navbar-inner">
            		<div class="container-fluid">
                		<a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
                  			<span class="icon-bar"></span> 
                  			<span class="icon-bar"></span> 
                  			<span class="icon-bar"></span>
                  		</a> 
                  		<a href="http://www.csus.edu/" title="Sacramento State Homepage">
                  			<img alt="Sacramento State logo" src="http://www.csus.edu/homep/monet/Images/header/logo-banner.png"/>
                  		</a>
                	</div>
            	</div>
         	</div>
    	
		</div>
	</div>
</div>




<div class="container" id="container"> 
  

  
  <!-- #main: page content goes here-->
  
  <div class="span-24 last" id="main" role="main"> <a id="mainContent"></a> <!-- accessibility, skip to main content target --> 
    
    <!-- #pageContent -->
    
    <div id="pageContent"> 
      
      <!-- #mainRegionContainer -->
      
      <div id="mainRegionContainer"> <?php echo $this->layout()->content; ?> </div>
      
      <!-- end #mainRegionContainer --> 
      
    </div>
    
    <!-- end #pageContent --> 
    
  </div>
  
  <!-- end #main --> 
  
</div>

<!-- end #container --> 

<!-- #bottom - make footer spread across entire page rather than be confined by 950 grid. -->

<div class="clear bottom">
  <div class="contentinfo" id="contentinfo" role="contentinfo"> 
    
    <!-- #contentinfo :contentinfo is landmark region for the footer -->
    
    <div id="contentInfoFooter">
      <div class="contentinfo-container" id="contentinfo_container">
        <div class="contentinfo span-24 last" id="contentinfo" role="contentinfo">
          <div class="footer-logo span-2"><a href="http://www.csus.edu"><img alt="Sac State Home" height="61" src="http://www.csus.edu/Monet/Images/global/footer_logo.png" width="59"/></a></div>
          <div class="address span-10" id="address">
            <div itemtype="http://schema.org/EducationalOrganization"><span itemprop="name">California State University, Sacramento</span><br/>
              <div itemprop="address" itemtype="http://schema.org/PostalAddress"><span itemprop="streetAddress">6000 J Street</span><br/>
                <span itemprop="addressLocality">Sacramento</span>, <span itemprop="addressRegion">CA</span> <span itemprop="postalCode">95819</span><br/>
                <span itemprop="telephone">(916) 278-6011</span></div>
            </div>
          </div>
          <div class="span-12 last">
            <div class="span-12 last footer-icons">
              <ul>
                <li><a href="http://www.facebook.com/sacstate" id="facebook_link"><img alt="facebook icon" height="32" src="http://www.csus.edu/homep//Monet/Images/icons/facebook.png" width="32"/></a></li>
                <li><a href="http://twitter.com/sacstate" id="twitter_link"><img alt="twitter icon" height="31" src="http://www.csus.edu/homep//Monet/Images/icons/twitter.png" width="32"/></a></li>
                <li><a href="http://www.youtube.com/SacStateVideo" id="youtube_link"><img alt="youtube icon" height="31" src="http://www.csus.edu/homep//Monet/Images/icons/youtube.png" width="32"/></a></li>
                <li><a href="http://www.flickr.com/photos/sacstate" id="flickr_link"><img alt="Flickr icon" height="31" src="http://www.csus.edu/homep//Monet/Images/icons/flickr.jpg" width="32"/></a></li>
              </ul>
            </div>
            <div class="span-12 last footer-links">
              <ul>
                <li><a href="http://www.csus.edu/contact/Comments.html">Comments &amp; Questions</a></li>
                <li><a href="http://www.csus.edu/About/AtoZ.html">A to Z Index</a></li>
                <li class="last"><a href="http://www.csus.edu/About/accessibility.html">Accessibility</a></li>
                <li class="last"><a href="http://www.collegeportraits.org/CA/CSUS">College Portrait</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <!-- end #contentinfo_container --> 
      
    </div>
    
    <!-- end #contentinfo --> 
    
  </div>
</div>

<!-- js at the bottom of page for faster load times --> 
<script src="http://www.csus.edu/cached/Colleges/1.0/js/application/cufon/cufon.js" type="text/javascript"></script> 
<script src="http://www.csus.edu/cached/Colleges/1.0/js/application/cufon/Trajan_Pro.font.js" type="text/javascript"></script> 
<script src="http://www.csus.edu/cached/Colleges/2.0/assets/js/monet-20-app.js" type="text/javascript"></script> 
<script src="/video/assets/js/osmf.js" type="text/javascript"></script> 

<!-- cufon to compensate for un-safe web fonts --> 
<script type="text/javascript">
//<![CDATA[
      Cufon.now();
    //]]>
</script> 


<!-- google anayltics --> 
<script src="http://www.google-analytics.com/ga.js" type="text/javascript">

</script> 
<script type="text/javascript">

//<![CDATA[
  var _gaq = _gaq || [];

  _gaq.push(['_setAccount', 'UA-798015-8']);

  _gaq.push(['_trackPageview']);

	(function() {

    	var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;

    	ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';

    	var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);

  	})();

	$(function () {

  		var track = function(x,y) {

	    _gaq.push(['_trackEvent', 'Sacramento State Course Videos', x, y]);

  	};

  var track_region = function (selector, name) { 

    $(selector).live('click', function(e){

      var _t = $(this);

      track(name,  (_t.text() || _t.children('img:first').attr('alt')));

    })

  };

  

   track_region('#logo a', 'Logo');

   track_region('#secondaryGlobalNav li a', 'Secondary Nav Link');

   track_region('.subLinks li a', 'Secondary Sub Nav Link');

   track_region('.globalNavigation ul li a', 'Primary Navigation Link');

   track_region('#quickLinks-menu li a', 'Quicklinks Links');

   track_region('#course_videos_link', 'Course Videos link');

   track_region('#live_streaming_link', 'Live Streaming link');

   track_region('#digital_media_link', 'Digital Media link');

   track_region('#faculty_media_server_link', 'Faculty Media Server link');

   track_region('#ask_a_consultant_link', 'Ask A Consultant link');

   track_region('#streaming_support_link', 'Streaming Support link');

   track_region('#email_service_desk_link', 'Email Service Desk link');

   track_region('#facebook_link', 'Facebook link');

   track_region('#twitter_link', 'Twitter link');

   track_region('#youtube_link', 'YouTube link');

   track_region('#flickr_link', 'flickr link');



});



    //]]>

</script> 

<!-- put nothing after this region -->

</body>
</html>