<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Video Library | Sacramento State</title>



<?php echo $this->partial('_library-css.phtml'); ?>

    
<?php echo $this->partial('_library-js-header.phtml'); ?>


</head>

<body>

<!--  #skip  Skip link as defined by webaim http://webaim.org/techniques/css/invisiblecontent/ -->
<div class="sr-only" id="skip"><a href="#mainContent">Skip to Main Content</a></div>

<?php echo $this->partial('_global-header.phtml'); ?>




<div class="main" id="main" role="main">	
	 
        <div id="page-wrapper">
	        <a id="mainContent"></a> <!-- accessibility, skip to main content target --> 
            <div class="row">
                <div class="col-lg-12">
                    
                    <div id="layout_content">
						<?php echo $this->layout()->content; ?>
					</div>
                    
                    
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            
        </div>
        <!-- /#page-wrapper -->


		
</div>


<footer class="ss-footer">
	<div class="container">
		
	
	<!-- #contentinfo :contentinfo is landmark region for the footer -->	
	
        <div class="contentinfo" id="contentinfo" role="contentinfo">
          <div class="col-md-1 address" id="address">
          	<div class="footer-logo"><a href="http://www.csus.edu"><img alt="Sac State Home"  src="http://www.csus.edu/Monet/Images/global/footer_logo.png" /></a></div>
          </div>
          
          <div class="col-md-3 address" id="address">
            <div itemtype="http://schema.org/EducationalOrganization">
            	<p>
            		<span itemprop="name">California State University, Sacramento</span><br/>
              		<span itemprop="streetAddress">6000 J Street</span><br/>
                	<span itemprop="addressLocality">Sacramento</span>, <span itemprop="addressRegion">CA</span> <span itemprop="postalCode">95819</span><br/>
                	<span itemprop="telephone">(916) 278-6011</span>
                </p>
            </div>
          </div>
          <div class="col-md-8">
            <div class="footer-icons">
              <ul class="nav nav-pills">
                <li><a href="http://www.facebook.com/sacstate" id="facebook_link"><img alt="facebook icon"  src="http://www.csus.edu/homep//Monet/Images/icons/facebook.png" /></a></li>
                <li><a href="http://twitter.com/sacstate" id="twitter_link"><img alt="twitter icon"  src="http://www.csus.edu/homep//Monet/Images/icons/twitter.png" /></a></li>
                <li><a href="http://www.youtube.com/SacStateVideo" id="youtube_link"><img alt="youtube icon"  src="http://www.csus.edu/homep//Monet/Images/icons/youtube.png" /></a></li>
                <li><a href="http://www.flickr.com/photos/sacstate" id="flickr_link"><img alt="Flickr icon"  src="http://www.csus.edu/homep//Monet/Images/icons/flickr.jpg" /></a></li>
              </ul>
            </div>
            <div class="footer-links">
              <ul class="nav nav-pills">
                <li><a href="http://www.csus.edu/contact/Comments.html">Comments &amp; Questions</a></li>
                <li><a href="http://www.csus.edu/About/AtoZ.html">A to Z Index</a></li>
                <li class="last"><a href="http://www.csus.edu/About/accessibility.html">Accessibility</a></li>
                <li class="last"><a href="http://www.collegeportraits.org/CA/CSUS">College Portrait</a></li>
              </ul>
            </div>
          </div>

    <!-- end #contentinfo_container --> 

	</div>
	</div>
</footer>








<!-- js at the bottom of page for faster load times --> 
<?php echo $this->partial('_library-js-footer.phtml'); ?>


<?php echo $this->partial('_admin-google-analytics.phtml'); ?>


<!-- put nothing after this region -->

</body>
</html>