

<div class="library-cover-image">
<div id="strobeplayer">
  
  <object id="sacstate_video" >
   <param name="movie" value='http://www2.csus.edu/video/assets/players/StrobeMediaPlayback.swf?src=<?php echo $this->playlistStream['hds_url']; ?>&poster=<?php echo $this->playlistStream['poster']; ?>&bufferingOverlay=false&optimizeInitialIndex=true&minContinuousPlayback=30&bufferTime=12&initialBufferTime=8&expandedBufferTime=10' />
<param name="allowFullScreen" value="true"/>
    <!--[if !IE]>-->
    <object type="application/x-shockwave-flash" data="http://www2.csus.edu/video/assets/players/StrobeMediaPlayback.swf?src=<?php echo $this->playlistStream['rtmp_url']; ?>&poster=<?php echo $this->playlistStream['poster']; ?>&bufferingOverlay=false&optimizeInitialIndex=true&minContinuousPlayback=30&bufferTime=12&initialBufferTime=8&expandedBufferTime=10" width="100%" height="540px">
<param name="allowFullScreen" value="true"/>     
 <!--<![endif]-->
      
      <div>
        <p>
          <video id="sacstate_video_html5" width="auto" height="100%" controls poster="<?php echo $this->playlistStream['poster']; ?>">
            <source src="<?php echo $this->playlistStream['hls_url']; ?>">
            Your browser does not support Flash Player 10.1 or the HTML5 video element. 
          </video>
        </p>
      </div>
      <!--[if !IE]>-->
    </object>
    <!--<![endif]-->
  </object>
</div>
<h1><?php echo $this->playlistStream['name']; ?></h1>
</div>

<div class="container">
    <div class="col-md-12">
         <h2>Playlist Videos</h2>

        <div class="well">
            <div id="myCarousel" class="carousel slide">
                
                <!-- Carousel items -->
                <div class="carousel-inner">
                    <div class="item active">
                        <div class="row">
                            <div class="col-sm-3"><a href="#x"><img src="http://lorempixel.com/250/250/sports/1" alt="Image" class="img-responsive"></a>
                            </div>
                            <div class="col-sm-3"><a href="#x"><img src="http://lorempixel.com/250/250/sports/2" alt="Image" class="img-responsive"></a>
                            </div>
                            <div class="col-sm-3"><a href="#x"><img src="http://lorempixel.com/250/250/sports/3" alt="Image" class="img-responsive"></a>
                            </div>
                            <div class="col-sm-3"><a href="#x"><img src="http://lorempixel.com/250/250/sports/4" alt="Image" class="img-responsive"></a>
                            </div>
                        </div>
                        <!--/row-->
                    </div>
                    <!--/item-->
                    <div class="item">
                        <div class="row">
                            <div class="col-sm-3"><a href="#x" class="thumbnail"><img src="http://lorempixel.com/250/250/sports/5" alt="Image" class="img-responsive"></a>
                            </div>
                            <div class="col-sm-3"><a href="#x" class="thumbnail"><img src="http://lorempixel.com/250/250/sports/6" alt="Image" class="img-responsive"></a>
                            </div>
                            <div class="col-sm-3"><a href="#x" class="thumbnail"><img src="http://lorempixel.com/250/250/sports/7" alt="Image" class="img-responsive"></a>
                            </div>
                            <div class="col-sm-3"><a href="#x" class="thumbnail"><img src="http://lorempixel.com/250/250/sports/8" alt="Image" class="img-responsive"></a>
                            </div>
                        </div>
                        <!--/row-->
                    </div>
                    <!--/item-->
                    <div class="item">
                        <div class="row">
                            <div class="col-sm-3"><a href="#x" class="thumbnail"><img src="http://lorempixel.com/250/250/sports/9" alt="Image" class="img-responsive"></a>
                            </div>
                            <div class="col-sm-3"><a href="#x" class="thumbnail"><img src="http://lorempixel.com/250/250/sports/10" alt="Image" class="img-responsive"></a>
                            </div>
                            <div class="col-sm-3"><a href="#x" class="thumbnail"><img src="http://lorempixel.com/250/250/city/1" alt="Image" class="img-responsive"></a>
                            </div>
                            <div class="col-sm-3"><a href="#x" class="thumbnail"><img src="http://lorempixel.com/250/250/city/2" alt="Image" class="img-responsive"></a>
                            </div>
                        </div>
                        <!--/row-->
                    </div>
                    <!--/item-->
                </div>
                <!--/carousel-inner--> <a class="left carousel-control" href="#myCarousel" data-slide="prev"> </a> 

                <a class="right carousel-control" href="#myCarousel" data-slide="next"> <span><i class="fa fa-angle-right-2x"></i></span> </a>
            </div>
            <!--/myCarousel-->
        </div>
        <!--/well-->
    </div>
</div>