<div class="container">
<div class="row">

            <div class="col-lg-12">
                <h3 class="page-header">Playlists</h3>
            </div>

            <div class="col-sm-3 col-xs-6">
                <a href="#">
                    <img class="img-responsive portfolio-item" src="http://lorempixel.com/500/300/">
                    <span class="video-play-sprite"></span>
                </a>
                <p>lorem ipsum title <span class="pull-right">20 videos</span></p>
            </div>

            <div class="col-sm-3 col-xs-6">
                <a href="#">
                    <img class="img-responsive portfolio-item" src="http://lorempixel.com/500/300/sports">
                    <span class="video-play-sprite"></span>
                </a>
                <p>lorem ipsum title <span class="pull-right">10 videos</span></p>
            </div>

            <div class="col-sm-3 col-xs-6">
                <a href="#">
                    <img class="img-responsive portfolio-item" src="http://lorempixel.com/500/300/people">
                    <span class="video-play-sprite"></span>
                </a>
                <p>lorem ipsum title <span class="pull-right">20 videos</span></p>
            </div>

            <div class="col-sm-3 col-xs-6">
                <a href="#">
                    <img class="img-responsive portfolio-item" src="http://lorempixel.com/500/300/city">
                    <span class="video-play-sprite"></span>
                </a>
                <p>lorem ipsum title <span class="pull-right">15 videos</span></p>
            </div>

        </div>
</div>

<div class="container">
<div class="row">

            <div class="col-sm-3 col-xs-6">
                <a href="#">
                    <img class="img-responsive portfolio-item" src="http://lorempixel.com/500/300/nature">
                    <span class="video-play-sprite"></span>
                </a>
                <p>lorem ipsum title <span class="pull-right">15 videos</span></p>
            </div>

            <div class="col-sm-3 col-xs-6">
                <a href="#">
                    <img class="img-responsive portfolio-item" src="http://lorempixel.com/500/300/sports/2">
                    <span class="video-play-sprite"></span>
                </a>
                <p>lorem ipsum title <span class="pull-right">22 videos</span></p>
            </div>

            <div class="col-sm-3 col-xs-6">
                <a href="#">
                    <img class="img-responsive portfolio-item" src="http://lorempixel.com/500/300/people/2">
                    <span class="video-play-sprite"></span>
                </a>
                <p>lorem ipsum title <span class="pull-right">30 videos</span></p>
            </div>

            <div class="col-sm-3 col-xs-6">
                <a href="#">
                    <img class="img-responsive portfolio-item" src="http://lorempixel.com/500/300/city/2">
                    <span class="video-play-sprite"></span>
                </a>
                <p>lorem ipsum title <span class="pull-right">10 videos</span></p>
            </div>

        </div>
</div>

<div class="container">
<div class="row">

            <div class="col-sm-3 col-xs-6">
                <a href="#">
                    <img class="img-responsive portfolio-item" src="http://lorempixel.com/500/300/food">
                    <span class="video-play-sprite"></span>
                </a>
                <p>lorem ipsum title <span class="pull-right">20 videos</span></p>
            </div>

            <div class="col-sm-3 col-xs-6">
                <a href="#">
                    <img class="img-responsive portfolio-item" src="http://lorempixel.com/500/300/sports/3">
                    <span class="video-play-sprite"></span>
                </a>
                <p>lorem ipsum title <span class="pull-right">20 videos</span></p>
            </div>

            <div class="col-sm-3 col-xs-6">
                <a href="#">
                    <img class="img-responsive portfolio-item" src="http://lorempixel.com/500/300/people/3">
                    <span class="video-play-sprite"></span>
                </a>
                <p>lorem ipsum title <span class="pull-right">20 videos</span></p>
            </div>

            <div class="col-sm-3 col-xs-6">
                <a href="#">
                    <img class="img-responsive portfolio-item" src="http://lorempixel.com/500/300/city/3">
                    <span class="video-play-sprite"></span>
                </a>
                <p>lorem ipsum title <span class="pull-right">20 videos</span></p>
            </div>

        </div>
</div>	